### IIR Filter

slam/rx_freq_x: 40
slam/rx_freq_y: 40
slam/rx_freq_z: 40
slam/rx_freq_theta: 40
slam/rx_freq_phy: 40
slam/rx_freq_psi: 40
slam/cutoff_pos_freq_x: 15
slam/cutoff_pos_freq_y: 15
slam/cutoff_pos_freq_z: 15
slam/cutoff_pos_freq_theta: 15
slam/cutoff_pos_freq_phy: 15
slam/cutoff_pos_freq_psi: 15
slam/cutoff_vel_freq_x: 4.4
slam/cutoff_vel_freq_y: 4.3
slam/cutoff_vel_freq_z: 4.3
slam/cutoff_vel_freq_theta: 4.3
slam/cutoff_vel_freq_phy: 4.3
slam/cutoff_vel_freq_psi: 10

