# Kawasaki IMU Board

kalman_filter/X/input_sigma: 0.15
kalman_filter/X/bias_sigma: 0.03
kalman_filter/X/measure_sigma: 0.04

kalman_filter/Y/input_sigma: 0.15
kalman_filter/Y/bias_sigma: 0.03
kalman_filter/Y/measure_sigma: 0.04

kalman_filter/Z/input_sigma: 0.35 # 0.12
kalman_filter/Z/bias_sigma: 0.003 # 0.003
kalman_filter/Z/measure_sigma: 0.005

#kalman_filterYawInput_sigma: 0.1
#kalman_filterYawBias_sigma: 0.001
#kalman_filterYawMeasure_sigma: 0.004

