# Optical Flow Kalman Filter on Kawasaki IMU Board


estimator/start_lower_thre: 0.305 
estimator/start_upper_thre: 0.4  #0.46
estimator/start_vel: 0.75 #0.25  

kalman_filter/X_Vel/input_sigma: 0.06 #0.05
kalman_filter/X_Vel/bias_sigma: 0.006 #0.005 test 0.002 good
kalman_filter/X_Vel/measure_sigma: 0.1


kalman_filter/Y_Vel/input_sigma: 0.06 #0.05
kalman_filter/Y_Vel/bias_sigma: 0.006 #0.005 test 0.002 good
kalman_filter/Y_Vel/measure_sigma: 0.1


kalman_filter/Z2/input_sigma: 0.35
kalman_filter/Z2/bias_sigma: 0.0006
kalman_filter/Z2/measure_sigma: 0.01
