gps:
  mavlink_pub_rate: 1.0
  topic_name: /gps
  test: true

bat:
  mavlink_pub_rate: 1.0
  percentage_mode: true
  topic_name: /battery_voltage_status
  test: true

heartbeat:
  mavlink_pub_rate: 0
  topic_name: /teleop_command/force_landing  # the motion of uav if heartbeat from gcs is timeout
  timeout: 3.0
  test: false

