
motor_info:
        motor_num: 1
        min_pwm: 0.55 # should calibrate ESC first, min_esc_range < min_pwm (e.g. min_esc_range = 0.5, min_pwm: 0.55). since the min_pwm is the lowest value for rotation, but with min_esc_range motor can not rotate
        max_pwm: 0.95 # should calibrate ESC first, max_esc_range = max_pwm