### PID control for quadcopter

controller/feedforward_flag: false

controller/pitch/ctrl_loop_rate: 40
controller/roll/ctrl_loop_rate: 40
controller/throttle/ctrl_loop_rate: 40
controller/yaw/ctrl_loop_rate: 40

# throttle 
controller/throttle/pos_p_gain: 250.0  #0.25 * 1000
controller/throttle/pos_i_gain: 250.0 #250.0  #0.25 * 1000
controller/throttle/pos_d_gain: 280.0  #0.28 * 1000
controller/throttle/const_i_ctrl_thre_land: 0.0
controller/throttle/offset: 1000
controller/throttle/pos_limit: 2000
controller/throttle/pos_p_limit: 150
controller/throttle/pos_i_limit: 900
controller/throttle/pos_d_limit: 180

# yaw 
controller/yaw/pos_p_gain: 450.0 #0.45 * 1000
controller/yaw/pos_i_gain: 20.0 #0.02 * 1000
controller/yaw/pos_d_gain: 0.0
controller/yaw/pos_limit: 100
controller/yaw/pos_p_limit: 100
controller/yaw/pos_i_limit: 50
controller/yaw/pos_d_limit: 50
controller/yaw/vel_value_limit: 0
#controller/yaw/i_enable_limit: 0.25

# pitch 
controller/pitch/pos_p_gain: 0.1 #old: 0.05
controller/pitch/pos_i_gain: 0.011336 # 0.01 * 1000  * 0.001744 * 0.65 # old : 0.05 * 1000
controller/pitch/pos_i_gain_hover: 0.005668 # 0.005 * 1000 * 0.001744 * 0.65
controller/pitch/pos_d_gain: 0.15 #old : 0.18
controller/pitch/vel_p_gain: 0.15  #old: 0.18
controller/pitch/vel_i_gain: 0.005668 #0.005 * 1000 * 0.001744 * 0.65
controller/pitch/offset: 0.0
controller/pitch/pos_limit: 0.30 #rook1 : 200 * 0.001744 * 0.65
controller/pitch/pos_p_limit: 0.20 #rook1 :100 * 0.001744 * 0.65
controller/pitch/pos_i_limit: 0.15 #rook1 : 100 * 0.001744 * 0.65
controller/pitch/pos_d_limit: 0.20 #rook1 : 100 * 0.001744 * 0.65
controller/pitch/vel_value_limit: 0.8
controller/pitch/i_enable_limit: 0.4

#  roll 
controller/roll/pos_p_gain: 0.1
controller/roll/pos_i_gain: 0.011336 #0.01 * 1000 * 0.001744 * 0.65 #old : 0.05 * 1000
controller/roll/pos_i_gain_hover: 0.005668  #0.005 * 1000 * 0.001744 * 0.65
controller/roll/pos_d_gain: 0.15
controller/roll/vel_p_gain: 0.15
controller/roll/vel_i_gain: 0.005668 #0.005 * 1000 * 0.001744 * 0.65
controller/roll/pos_limit: 0.30 #rook1 : 200 * 0.001744 * 0.65
controller/roll/pos_p_limit: 0.20 #rook1 :100 * 0.001744 * 0.65
controller/roll/pos_i_limit: 0.15 #rook1 : 100 * 0.001744 * 0.65
controller/roll/pos_d_limit: 0.20 #rook1 : 100 * 0.001744 * 0.65
controller/roll/vel_value_limit: 0.8
controller/roll/i_enable_limit: 0.4
controller/roll/offset: 0

#others
controller/land_gain_slow_rate: 0.3