# Kawasaki IMU Board

# x axis
kalman_filter/X/input_sigma: 0.05
kalman_filter/X/bias_sigma: 0.05
kalman_filter/X/measure_sigma: 0.04

# y axis
kalman_filter/Y/input_sigma: 0.05
kalman_filter/Y/bias_sigma: 0.05
kalman_filter/Y/measure_sigma: 0.04

# z axis
kalman_filter/Z/input_sigma: 0.35 
kalman_filter/Z/bias_sigma: 0.003 
kalman_filter/Z/measure_sigma: 0.005

#yaw axis
#kalmanFilterYawInput_sigma: 0.1
#kalmanFilterYawBias_sigma: 0.001
#: 0.004

