<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro"  >

  <xacro:macro name="link_color">
    <material name="white">
      <color rgba="0.85 0.85 .85 1"/>
    </material>
  </xacro:macro>

  <xacro:macro name="hand_color">
    <material name="blue">
      <color rgba="0.0 0.0 0.85 1"/>
    </material>
  </xacro:macro>

  <xacro:property name="hand_radius" value=".07" />
  <xacro:property name="link_length" value=".15" />
  <xacro:property name="link_radius" value=".03" />

  <xacro:macro name="doraemon_hand" params="parent"> 


    <joint name="hand_root_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="hand_link"/>
      <origin rpy="0  0 0" xyz="0 0 ${-link_length*.5}"/>
    </joint>

    <link name="hand_link">
      <visual>
        <geometry>
          <cylinder length="${link_length}" radius="${link_radius}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="hand_base_joint" type="fixed">
      <parent link="hand_link"/>
      <child link="hand_base"/>
      <origin rpy="0 0 0" xyz="0 0 ${-link_length*.5}"/>
    </joint>

    <link name="hand_base">
      <visual>
        <geometry>
          <cylinder length="${link_length*.4}" radius="${hand_radius*.9}"/>
        </geometry>
        <xacro:link_color />
      </visual>
    </link>

    <joint name="hand_joint" type="fixed">
      <parent link="base_link"/>
      <child link="hand_ball"/>
      <origin rpy="0 0 0" xyz="0 0 ${-link_length * 1.2}"/>
    </joint>

    <link name="hand_ball">
      <visual>
        <geometry>
          <sphere radius="${hand_radius}"/>
        </geometry>
        <xacro:hand_color />
      </visual>
    </link>

  </xacro:macro>

</robot>