demo_transform_node/joint_num: 3
demo_transform_node/node_num: 5

#normal-ku

#node0: pi/2 pi/2 pi/2
demo_transform_node/node0_pos_roll_i_term: 10 
demo_transform_node/node0_pos_pitch_i_term: 15
demo_transform_node/node0_att_roll_pitch_p_gain: 100 
demo_transform_node/node0_att_roll_d_gain: 51 
demo_transform_node/node0_att_pitch_d_gain: 51 
demo_transform_node/node0_joint0_angle: 1.5708
demo_transform_node/node0_joint1_angle: 1.5708
demo_transform_node/node0_joint2_angle: 1.5708

#node1: 0 pi/2 0
demo_transform_node/node1_pos_roll_i_term: 10 
demo_transform_node/node1_pos_pitch_i_term: 15 
demo_transform_node/node1_att_roll_pitch_p_gain: 100
demo_transform_node/node1_att_roll_d_gain: 81
demo_transform_node/node1_att_pitch_d_gain: 51
demo_transform_node/node1_joint0_angle: 0
demo_transform_node/node1_joint1_angle: 1.5708
demo_transform_node/node1_joint2_angle: 0

#node2: pi/2 pi/2 pi/2
demo_transform_node/node2_pos_roll_i_term: 10 
demo_transform_node/node2_pos_pitch_i_term: 15
demo_transform_node/node2_att_roll_pitch_p_gain: 100 
demo_transform_node/node2_att_roll_d_gain: 51 
demo_transform_node/node2_att_pitch_d_gain: 51 
demo_transform_node/node2_joint0_angle: 1.5708
demo_transform_node/node2_joint1_angle: 1.5708
demo_transform_node/node2_joint2_angle: 1.5708

#node3: 0 pi/2 0
demo_transform_node/node3_pos_roll_i_term: 10 
demo_transform_node/node3_pos_pitch_i_term: 15 
demo_transform_node/node3_att_roll_pitch_p_gain: 100
demo_transform_node/node3_att_roll_d_gain: 81
demo_transform_node/node3_att_pitch_d_gain: 51
demo_transform_node/node3_joint0_angle: 0
demo_transform_node/node3_joint1_angle: 1.5708
demo_transform_node/node3_joint2_angle: 0

#node4: pi/2 pi/2 pi/2
demo_transform_node/node4_pos_roll_i_term: 10 
demo_transform_node/node4_pos_pitch_i_term: 15
demo_transform_node/node4_att_roll_pitch_p_gain: 100 
demo_transform_node/node4_att_roll_d_gain: 51 
demo_transform_node/node4_att_pitch_d_gain: 51 
demo_transform_node/node4_joint0_angle: 1.5708
demo_transform_node/node4_joint1_angle: 1.5708
demo_transform_node/node4_joint2_angle: 1.5708

