# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: aerial_robot/pose
        pose2d: aerial_robot/ground_pose
        child_frame_id: aerial_robot/base_link
        parent_frame_id: world
