### PID control for quadcopter

controller/pitch/ctrl_loop_rate: 40
controller/roll/ctrl_loop_rate: 40
controller/throttle/ctrl_loop_rate: 40
controller/yaw/ctrl_loop_rate: 40

# throttle 
controller/throttle/pos_p_gain: 0.25
controller/throttle/pos_i_gain: 0.25
controller/throttle/pos_d_gain:  0.28
controller/throttle/pos_p_gain_land: 0.1
controller/throttle/pos_i_gain_land: 0.03
controller/throttle/pos_d_gain_land: 0.2
controller/throttle/const_p_ctrl_thre_land: -0.1
controller/throttle/const_p_term_lev1_value_land: -20
controller/throttle/const_p_term_lev2_value_land: -40
controller/throttle/const_i_ctrl_thre_land: -0.25
controller/throttle/const_i_term_value_land: 0.5
controller/throttle/offset: 1000
controller/throttle/pos_limit: 1800
controller/throttle/pos_p_limit: 150
controller/throttle/pos_p_limit_hover: 50
controller/throttle/pos_i_limit: 1000
controller/throttle/pos_d_limit: 180
controller/throttle/vel_value_limit_hover: 0
controller/throttle/i_enable_limit_hover: 0.1

# pitch 
controller/pitch/pos_p_gain: 0.08
controller/pitch/pos_i_gain: 0.05 # old : 0.05
controller/pitch/pos_i_gain_hover: 0.005
controller/pitch/pos_d_gain: 0.5 #for mocap: 0.5,  for opt 0.4
controller/pitch/vel_p_gain: 0.5 #for mocap: 0.48, for opt 0.4
controller/pitch/vel_i_gain: 0.005 
controller/pitch/pos_limit: 200 # rook1: 200
controller/pitch/pos_p_limit: 100 #rook1 :100
controller/pitch/pos_i_limit: 100 #rook1 :100 
controller/pitch/pos_d_limit: 100 #rook1 :100
controller/pitch/vel_value_limit: 0.8
controller/pitch/i_enable_limit: 1.0
controller/pitch/offset: 0

#  roll 
controller/roll/pos_p_gain: 0.08
controller/roll/pos_i_gain: 0.05 #old : 0.05
controller/roll/pos_i_gain_hover: 0.005
controller/roll/pos_d_gain: 0.5 # for mocap 0.5, for opt 0.4
controller/roll/vel_p_gain: 0.5 # for mocap 0.5, for opt 0.4
controller/roll/vel_i_gain: 0.005
controller/roll/pos_limit: 200 #rook1 : 200
controller/roll/pos_p_limit: 200 #rook1 :100
controller/roll/pos_i_limit: 200 #rook1 : 100
controller/roll/pos_d_limit: 200 #rook1 : 100
controller/roll/vel_value_limit: 0.8
controller/roll/i_enable_limit: 1.0
controller/roll/offset: 0 #roll is reversed!!

# yaw 
controller/yaw/pos_p_gain: 0.15 # 0.15
controller/yaw/pos_i_gain: 0.01
controller/yaw/pos_d_gain: 0.0
controller/yaw/pos_limit: 100 #200 is too big => lots of problem
controller/yaw/pos_p_limit: 100
controller/yaw/pos_i_limit: 20
controller/yaw/pos_d_limit: 50
controller/yaw/vel_value_limit: 0
controller/yaw/i_enable_limit: 0.4
