dragon:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # for control bridge
    joint_num: 6
    joint1: #pitch
        init_angle: 0
    joint2: #yaw
        init_angle: 1.57
    joint3: #pitch
        init_angle: 0
    joint4: #yaw
        init_angle: 1.57
    joint5: #pitch
        init_angle: 0
    joint6: #yaw
        init_angle: 1.57

    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint1_pitch
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint1_yaw
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint3_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint2_pitch
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint4_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint2_yaw
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint5_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint3_pitch
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint6_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint3_yaw
        pid: {p: 50.0, i: 0.01, d: 2.0}

    gimbal_num: 8
    gimbal1: #roll
        init_angle: 0
    gimbal2: #pitch
        init_angle: 0
    gimbal3: #roll
        init_angle: 0
    gimbal4: #pitch
        init_angle: 0
    gimbal5: #roll
        init_angle: 0
    gimbal6: #pitch
        init_angle: 0
    gimbal7: #roll
        init_angle: 0
    gimbal8: #pitch
        init_angle: 0

    gimbal1_position_controller:
        type: effort_controllers/JointPositionController
        joint: gimbal1_roll
        pid: {p: 50.0, i: 0.01, d: 0.0}
    gimbal2_position_controller:
        type: effort_controllers/JointPositionController
        joint: gimbal1_pitch
        pid: {p: 50.0, i: 0.01, d: 0.0}
    gimbal3_position_controller:
        type: effort_controllers/JointPositionController
        joint: gimbal2_roll
        pid: {p: 50.0, i: 0.01, d: 0.0}
    gimbal4_position_controller:
        type: effort_controllers/JointPositionController
        joint: gimbal2_pitch
        pid: {p: 50.0, i: 0.01, d: 0.0}
    gimbal5_position_controller:
        type: effort_controllers/JointPositionController
        joint: gimbal3_roll
        pid: {p: 50.0, i: 0.01, d: 0.0}
    gimbal6_position_controller:
        type: effort_controllers/JointPositionController
        joint: gimbal3_pitch
        pid: {p: 50.0, i: 0.01, d: 0.0}
    gimbal7_position_controller:
        type: effort_controllers/JointPositionController
        joint: gimbal4_roll
        pid: {p: 50.0, i: 0.01, d: 0.0}        
    gimbal8_position_controller:
        type: effort_controllers/JointPositionController
        joint: gimbal4_pitch
        pid: {p: 50.0, i: 0.01, d: 0.0}
        
    # test for non-attitude control mode
    baselink_name: link2
    attitude_controller:
        type: flight_controllers/SimulationAttitudeController
        